version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/goms-app

permissions: # codedeploy에서 EC2서버로 넘겨준 파일 모두 ec2-user 권한 부여
  - object: /home/ec2-user/goms-app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: execute-deploy.sh
      timeout: 60