name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: sunggil-5125/goms
            stage: main
            yaml: >
              name: goms-backend

            app: java@11

            options:
              ports: 8080
              env:
                - name: DB_DRIVER
                  value: ${{ secrets.DB_DRIVER }}
                - name: DB_URL
                  value: ${{ secrets.DB_URL }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: REDIS_HOST
                  value: ${{ secrets.REDIS_HOST }}
                - name: REDIS_PORT
                  value: ${{ secrets.REDIS_PORT }}
                - name: JPA_DDL_AUTO
                  value: ${{ secrets.JPA_DDL_AUTO }}
                - name: JWT_ACCESS_SECRET
                  value: ${{ secrets.JWT_ACCESS_SECRET }}
                - name: JWT_REFRESH_SECRET
                  value: ${{ secrets.JWT_REFRESH_SECRET }}
                - name: JWT_ACCESS_EXP
                  value: ${{ secrets.JWT_ACCESS_EXP }}
                - name: JWT_REFRESH_EXP
                  value: ${{ secrets.JWT_REFRESH_EXP }}
                - name: GAUTH_CLIENTID
                  value: ${{ secrets.GAUTH_CLIENTID }}
                - name: CLIENT_SECRET
                  value: ${{ secrets.CLIENT_SECRET }}
                - name: REDIRECT_URI
                  value: ${{ secrets.REDIRECT_URI }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
